# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - script: echo Job1!!, Updated on 28th-Dec-2024, New Update on 3rd-Jan-2025, New!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job2
  steps:
  - script: echo Job2! Printing added on 4th-Jan-2025!!
    displayName: 'Run a one-line script' 
